Traceback (most recent call last):
  File "/home/student/HumanChoicePrediction/HumanChoicePrediction-1/StrategyTransfer.py", line 110, in <module>
    env_model = environments.LSTM_env.LSTM_env(env_name, config=config)
  File "/home/student/HumanChoicePrediction/HumanChoicePrediction-1/environments/environment.py", line 21, in __init__
    self.use_user_vector = config["use_user_vector"]
  File "/anaconda/envs/final_project_env/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'use_user_vector'